function XRT_3DAnlys_ParameterSave(XRT_Opts,XRT_3DAnlys_Opts,XRT_ImgPrc_Opts,Batch3DAnlys_Iter)
%XRT_3DAnlys_ParameterSave Save image processing parameter.
% 
%   Used for XRT_3DAnlys package.
% 
%   Author
%   --------
%   Frederik Doerr, Aug 2020 (MATLAB R2019b)
%   frederik.doerr(at)strath.ac.uk | CMAC (http://www.cmac.ac.uk/)
%   Github: https://github.com/frederik-d/XRT_3DAnlys


fileID = fopen(sprintf('%s_XRT_ImgPrc_Parameter.txt',XRT_3DAnlys_Opts.ExpShorthand),'wt');
ImgProcessing_Parameter_header = { ...
            'Operator',XRT_3DAnlys_Opts.Operator; ... 
            'Date',XRT_Opts.datestring; ...
            'Operating System',XRT_3DAnlys_Opts.localPC_name; ... 
            'ExpShorthand',XRT_3DAnlys_Opts.ExpShorthand; ...
            'Input_FolderPath',char(XRT_Opts.ImgPrc_3DAnlys.Input_FolderPath(Batch3DAnlys_Iter)); ...
            'Output_FolderPath',char(XRT_Opts.ImgPrc_3DAnlys.Output_FolderPath(Batch3DAnlys_Iter)); ...
            '3DAnlys_2D_Ref',char(XRT_Opts.ImgPrc_3DAnlys.ImgPrc_Param_REF(Batch3DAnlys_Iter)); ...
            };   
    for i = 1:length(ImgProcessing_Parameter_header)
        fprintf(fileID,XRT_3DAnlys_Opts.formatSpec_s_s,ImgProcessing_Parameter_header{i,:});
    end  


fprintf(fileID,'\n - - - - - - - - - - - - - - - \nXRT_3DAnlys_Opts\n  - - - - - - - - - - - - - - - \n');
XRT_3DAnlys_Opts_Parameter_dat = { ...
        'ROI_Reduction_Check',sprintf('%d',XRT_3DAnlys_Opts.ROI_Reduction_Check);  ...
        'NoiseReduction3D',sprintf('%d',XRT_3DAnlys_Opts.NoiseReduction3D);  ...  
        'VolumeAnlys_On',sprintf('%d',XRT_3DAnlys_Opts.VolumeAnlys_On);  ...
        'PorosAnlys3D_On',sprintf('%d',XRT_3DAnlys_Opts.PorosAnlys3D_On); ...
        'BinSegment3D_On',sprintf('%d',XRT_3DAnlys_Opts.BinSegment3D_On); ...
        'ImagePixelSize',sprintf('%.3f',XRT_3DAnlys_Opts.ImagePixelSize); ...
        'ImagePixelSize_rS',sprintf('%.3f',XRT_3DAnlys_Opts.ImagePixelSize_rS); ...
        'DataResizeFactor',sprintf('%.0f',XRT_3DAnlys_Opts.DataResizeFactor); ...
        'VolumeAnlys_Concave_Anlys',sprintf('%d',XRT_3DAnlys_Opts.VolumeAnlys_Concave_Anlys);  ...
        'VolumeAnlys_3DDescriptors',sprintf('%d',XRT_3DAnlys_Opts.VolumeAnlys_3DDescriptors);  ...
        'VolExport_SurfRend_Check',sprintf('%d',XRT_3DAnlys_Opts.VolExport_SurfRend_Check)  ...
        };
for i = 1:length(XRT_3DAnlys_Opts_Parameter_dat)
    fprintf(fileID,XRT_3DAnlys_Opts.formatSpec_s_s,XRT_3DAnlys_Opts_Parameter_dat{i,:});
end

fprintf(fileID,'\n - - - - - - - - - - - - - - - \nXRT_ImgPrc_Opts\n  - - - - - - - - - - - - - - - \n');

XRT_ImgPrc_Opts_Parameter_dat = { ...
        'Img_Polarity',sprintf('%.0f',XRT_ImgPrc_Opts.Img_Polarity);  ...
        'ImgPrc_imFilter',sprintf('%s',XRT_ImgPrc_Opts.ImgPrc_imFilter);  ...  
        'ImgPrc_imFilter_Size',sprintf('%.0f',XRT_ImgPrc_Opts.ImgPrc_imFilter_Size);  ...
        'ImgPrc_imFilter_Parameter_1',sprintf('%.0f',XRT_ImgPrc_Opts.ImgPrc_imFilter_Parameter_1);  ...
        'ImgPrc_bw_thresMethod',sprintf('%s',XRT_ImgPrc_Opts.ImgPrc_bw_thresMethod);  ...  
        'ImgPrc_bw_thresVal_Manual',sprintf('%.0f',XRT_ImgPrc_Opts.ImgPrc_bw_thresVal_Manual);  ... 
        'NoiseReduction2D_ClearBorder',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction2D.ClearBorder);  ...
        'NoiseReduction2D_WhiteNoise_Size',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction2D.WhiteNoise_Size);  ...
        'NoiseReduction2D_Close_Size',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction2D.Close_Size);  ...
        'NoiseReduction2D_Open_Size',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction2D.Open_Size);  ...
        'NoiseReduction2D_BlackNoise_Size',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction2D.BlackNoise_Size);  ...
        'NoiseReduction3D_Method',sprintf('%s',XRT_ImgPrc_Opts.NoiseReduction3D.Method);  ...  
        'NoiseReduction3D_ClearBorder',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction3D.ClearBorder);  ...
        'NoiseReduction3D_Close_Size_V',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction3D.Close_Size_V);  ...
        'NoiseReduction3D_Open_Size_V',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction3D.Open_Size_V);  ...
        'NoiseReduction3D_Close_Size_V',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction3D.Close_Size_V);  ...
        'NoiseReduction3D_Close_Size_V_ROI',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction3D.Close_Size_V_ROI);  ...
        'NoiseReduction3D_Open_Size_V_ROI',sprintf('%.0f',XRT_ImgPrc_Opts.NoiseReduction3D.Open_Size_V_ROI);  ...
        'ROI_Method',sprintf('%s',XRT_ImgPrc_Opts.ROI_Method);  ...  
        'ROI_Method_ShrinkWrap_Size',sprintf('%.0f',XRT_ImgPrc_Opts.ROI_Method_ShrinkWrap_Size);  ... 
        'Watershed_Shrinkwrap_Method',sprintf('%s',XRT_ImgPrc_Opts.Watershed.Shrinkwrap_Method); ...
        'Watershed_Shrinkwrap_Size',sprintf('%.0f',XRT_ImgPrc_Opts.Watershed.Shrinkwrap_Size); ...
        'Watershed_imextendedmin_Size',sprintf('%.0f',XRT_ImgPrc_Opts.Watershed.imextendedmin_Size); ...
        };
for i = 1:length(XRT_ImgPrc_Opts_Parameter_dat)
    fprintf(fileID,XRT_3DAnlys_Opts.formatSpec_s_s,XRT_ImgPrc_Opts_Parameter_dat{i,:});
end
fclose(fileID);